In [1]:
import pandas as pd

In [2]:
import numpy as np

# doc_list

In [3]:
doc_list = pd.read_csv("doctors_list_t8.csv")

In [4]:
pd.isnull(doc_list).sum()

Id             0
initial        0
href           0
name           0
specialties    0
address        0
zip            0
dtype: int64

In [4]:
doc_list.head()

,Id,initial,href,name,specialties,address,zip
0,3886560,a,/doctors/Dr_Enenge_ABodjedi,Enenge Abodjedi,['Psychiatrist'],"Stamford, CT 06902",06902
1,3886561,a,/doctors/Dr_Brady_AHearn,Brady J A'Hearn,['Pediatrician'],"Iowa City, IA 52242",52242
2,3886562,a,/doctors/Dr_Yousif_Arahim,Yousif A-Rahim,"['Gastroenterologist (digestive)', ' Internist']","Aiea, HI 96701",96701
3,3886563,a,/doctors/Dr_Noor_Al_Khori,Noor Al Khori,['Student'],"Grand Rapids, MI 49503",49503
4,3886564,a,/doctors/Dr_Salam_Al-Hafidh,Salam N Al-Hafidh,['Pediatrician'],"Richland Hills, TX 76180",76180

In [5]:
doc_list.tail()

,Id,initial,href,name,specialties,address,zip
1294498,5181716,i,/dentists/Dr_Micheal_Izzo,Michael A Izzo,['Dentist'],"Lincoln Park, MI 48146",48146
1294499,5181717,i,/doctors/Dr_Philip_Izzo,Philip M Izzo,['Psychiatrist'],"Media, PA 19063",19063
1294500,5181718,i,/dentists/Dr_Steven_Izzo,Steven R Izzo,['Dentist'],"Ridgewood, NY 11385",11385
1294501,5181719,i,/dentists/Dr_Steven_Izzo_2,Steven Izzo,['Dentist'],"Brooklyn, NY 11228",11228
1294502,5181720,i,/doctors/Dr_Timothy_Izzo,Timothy J Izzo,"['Family Practitioner', ' Primary Care Doctor']","Grand Ledge, MI 48837",48837

In [6]:
np.shape(doc_list) # see the number of rows and columns

(1294503, 7)

- We have 1294503 doctors in the data set

In [7]:
r = lambda x: x.lstrip("/")

In [8]:
doc_list.href = doc_list.href.apply(r) # split the href into title and the prof_name

In [9]:
doc_list['title'], doc_list['prof_name'] = doc_list['href'].str.split('/',1).str

In [10]:
doc_list = doc_list.drop('href',1)

In [11]:
doc_list.tail()

,Id,initial,name,specialties,address,zip,title,prof_name
1294498,5181716,i,Michael A Izzo,['Dentist'],"Lincoln Park, MI 48146",48146,dentists,Dr_Micheal_Izzo
1294499,5181717,i,Philip M Izzo,['Psychiatrist'],"Media, PA 19063",19063,doctors,Dr_Philip_Izzo
1294500,5181718,i,Steven R Izzo,['Dentist'],"Ridgewood, NY 11385",11385,dentists,Dr_Steven_Izzo
1294501,5181719,i,Steven Izzo,['Dentist'],"Brooklyn, NY 11228",11228,dentists,Dr_Steven_Izzo_2
1294502,5181720,i,Timothy J Izzo,"['Family Practitioner', ' Primary Care Doctor']","Grand Ledge, MI 48837",48837,doctors,Dr_Timothy_Izzo

In [17]:
doc_list.title.value_counts()

doctors     1095990
dentists     198513
Name: title, dtype: int64

There are 1095990 doctors and 198513 dentists

In [12]:
import re

In [24]:
rs = lambda x: re.sub('[^a-zA-Z\']+', ' ', x)

In [25]:
doc_list.specialties = doc_list.specialties.apply(rs) # clean the specialties columns

In [26]:
doc_list.head()

,Id,initial,name,specialties,address,zip,title,prof_name
0,3886560,a,Enenge Abodjedi,'Psychiatrist',"Stamford, CT 06902",06902,doctors,Dr_Enenge_ABodjedi
1,3886561,a,Brady J A'Hearn,'Pediatrician',"Iowa City, IA 52242",52242,doctors,Dr_Brady_AHearn
2,3886562,a,Yousif A-Rahim,'Gastroenterologistdigestive''Internist',"Aiea, HI 96701",96701,doctors,Dr_Yousif_Arahim
3,3886563,a,Noor Al Khori,'Student',"Grand Rapids, MI 49503",49503,doctors,Dr_Noor_Al_Khori
4,3886564,a,Salam N Al-Hafidh,'Pediatrician',"Richland Hills, TX 76180",76180,doctors,Dr_Salam_Al-Hafidh

In [21]:
np.shape(doc_list)

(1294503, 8)

In [31]:
words = []
for i in doc_list.specialties:
    words += [i]

In [35]:
words_clean = re.sub('[^a-zA-Z]+', '/', str(words))

In [37]:
#count the specialties
specialist = {}
wordsplit = words_clean.split('/')
for word in wordsplit:
    if word in specialist :
        specialist[word]=specialist[word]+1
    else:
        specialist[word] = 1

In [46]:
sorted(specialist.items(), key=lambda x: x[1],reverse=True)

[('Internist', 222313),
 ('Dentist', 198510),
 ('PrimaryCareDoctor', 139732),
 ('FamilyPractitioner', 131692),
 ('SurgicalSpecialist', 100403),
 ('Pediatrician', 92566),
 ('Psychologist', 87175),
 ('Psychiatrist', 57374),
 ('Student', 56887),
 ('ObstetricianGynecologistOBGYN', 52807),
 ('Anesthesiologistpaincontrol', 52793),
 ('Radiologist', 48060),
 ('EmergencyPhysician', 46557),
 ('OrthopaedicSurgeon', 31876),
 ('Cardiologistheart', 31593),
 ('Pathologist', 23725),
 ('Ophthalmologisteyes', 23133),
 ('OncologySpecialistcancer', 22076),
 ('Neurologistbrain', 20461),
 ('nervoussystem', 20460),
 ('Gastroenterologistdigestive', 16900),
 ('PediatricSpecialist', 15693),
 ('GeneralPractitioner', 15451),
 ('Dermatologistskin', 14867),
 ('Pulmonologistlungs', 14723),
 ('Otolaryngologistear', 13356),
 ('nose', 13356),
 ('throat', 13356),
 ('Urologist', 13183),
 ('CriticalCareSpecialist', 11958),
 ('GeriatricSpecialistelderlycare', 11838),
 ('Physiatristphysical', 11498),
 ('rehabilitation', 11498),
 ('Nephrologistkidney', 11286),
 ('PlasticSurgerySpecialist', 10253),
 ('HematologySpecialist', 9746),
 ('InfectiousDiseaseSpecialistvirus', 9490),
 ('bacteria', 9490),
 ('parasites', 9490),
 ('PainManagementSpecialist', 8852),
 ('PreventiveMedicineWellness', 8791),
 ('Endocrinologistdiabetes', 8447),
 ('hormones', 8447),
 ('NeurologicalSurgeon', 7017),
 ('PediatricAdolescentPsychiatrist', 6845),
 ('Rheumatologist', 6329),
 ('SportsMedicineSpecialist', 6312),
 ('AllergyImmunologySpecialist', 5931),
 ('CardiothoracicSurgeon', 5802),
 ('Hospitalist', 5081),
 ('NuclearMedicineSpecialist', 4492),
 ('RadiationOncology', 4378),
 ('SleepMedicineSpecialist', 4105),
 ('HospicePalliativeSpecialist', 3048),
 ('AdolescentSpecialist', 2857),
 ('AddictionMedicineSpecialist', 2345),
 ('ColorectalSurgeoncolonrectum', 1961),
 ('PediatricSurgeon', 1400),
 ('Geneticist', 1335),
 ('OralMaxillofacialSurgeon', 1114),
 ('Hepatologist', 575),
 ('Osteopath', 485),
 ('BariatricSpecialistobesity', 265),
 ('Phlebologist', 196),
 ('ClinicalPharmacologist', 122),
 ('LegalMedicine', 98),
 ('FemalePelvicMedicineandReconstructiveSurgeon', 60),
 ('Specialist', 46),
 ('EpilepsySpecialistrnEpilepsySpecialist', 28),
 ('UrgentCare', 8),
 ('BrainInjuryMedicineSpecialist', 6),
 ('ClinicalInformatics', 3),
 ('', 2),
 ('nervoussy', 1)]

the TOP 10 	specialties are:
 - ('Internist', 222313),
 - ('Dentist', 198510),
 - ('PrimaryCareDoctor', 139732),
 - ('FamilyPractitioner', 131692),
 - ('SurgicalSpecialist', 100403),
 - ('Pediatrician', 92566),
 - ('Psychologist', 87175),
 - ('Psychiatrist', 57374),
 - ('Student', 56887),
 - ('ObstetricianGynecologistOBGYN', 52807)

In [47]:
specialist_table = pd.DataFrame.from_dict(specialist, orient='index')

# doc_panel

In [4]:
doc_panel = pd.read_csv("doctors_panel_t8.csv")

In [5]:
doc_panel.head()

,Id,href,years_of_exp,overall_rating,n_ratings,n_reviews,avg_wating,Ease_of_Appointment,Promptness,Courteous_Staff,...,Caring_Manner,Pain_Minimized,Satisfaction,n_5,n_4,n_3,n_2,n_1,address,crawl_date
0,9206066,/dentists/Dr_Aamir_M_Sheikh,10.0,0.0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"9105 All Saints Rd, Laurel, MD, 20723",2016-09-06 20:53:49
1,9206067,/dentists/Dr_Aamir_Shah_2,NaN,4.5,3,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"7872 Walker St, La Palma, CA, 90623",2016-09-06 20:53:51
2,9206068,/dentists/Dr_Aalie_Sagar,NaN,3.5,3,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10842 Potranco Rd, San Antonio, TX, 78251",2016-09-06 20:53:54
3,9206069,/dentists/Dr_Aan_Litvinov,NaN,1.0,1,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1740 Culver Rd, Rochester, NY, 14609",2016-09-06 20:53:55
4,9206070,/dentists/Dr_Aarika_Anderson_Elter,NaN,5.0,1,1,NaN,3.5,NaN,NaN,...,5.0,5.0,NaN,1.0,0.0,0.0,0.0,0.0,"1708 E 44th St, Tacoma, WA, 98404",2016-09-06 20:54:01

In [11]:
doc_panel.tail()

,Id,href,years_of_exp,overall_rating,n_ratings,n_reviews,avg_wating,Ease_of_Appointment,Promptness,Courteous_Staff,...,Caring_Manner,Pain_Minimized,Satisfaction,n_5,n_4,n_3,n_2,n_1,address,crawl_date
1293677,10499745,/doctors/Dr_Ramy_Doss,25.0,4.5,21,11,33 minutes,5.0,4.0,4.5,...,NaN,NaN,NaN,16.0,2.0,1.0,2.0,0.0,"10293 N 92nd St, Scottsdale, AZ, 85258",2016-09-16 20:03:43
1293678,10499746,/doctors/Dr_Ramzi_Khazen,11.0,0.0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"60 Hospital Rd, Leominster, MA, 01453",2016-09-16 20:03:45
1293679,10499747,/doctors/Dr_Randall_Edson,37.0,3.0,2,1,10 minutes,5.0,3.5,5.0,...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0,"200 1st St Sw, Rochester, MN, 55905",2016-09-16 20:03:45
1293680,10499748,/doctors/Dr_Randall_Farrar,26.0,4.5,18,1,17 minutes,4.0,4.5,4.5,...,NaN,NaN,NaN,14.0,1.0,0.0,0.0,3.0,"1155 Jadwin Ave, Richland, WA, 99352",2016-09-16 20:03:47
1293681,10499749,/doctors/Dr_Randall_Finken,49.0,5.0,2,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"3909 Woodley Rd, Toledo, OH, 43606",2016-09-16 20:03:48

In [7]:
rew_panel = pd.read_csv("reviews_panel_t8.csv")

In [8]:
rew_panel.head()

,Id,review_id,href,overall_rating,Ease_of_Appointment,Promptness,Courteous_Staff,Accurate_Diagnosis,Bedside_Manner,Spends_Time_with_Me,...,Advanced_Technology,Caring_Manner,Pain_Minimized,Satisfaction,date,reviewer,title,content,helpful_vote,crawl_date
0,12949966,23507540,/dentists/Dr_Aarika_Anderson_Elter,5,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,5.0,5.0,NaN,2012-11-16,NaN,Great results,Dr. Anderson explained in detail my options fo...,NaN,2016-09-06 20:54:01
1,12949967,27184431,/dentists/Dr_Aamir_Wahab,5,5.0,NaN,NaN,NaN,NaN,NaN,...,5.0,5.0,5.0,5.0,2015-03-15,Brad s.,implant,Had an implant done and it was painless. I cou...,NaN,2016-09-06 20:54:10
2,12949968,26307282,/dentists/Dr_Aanal_Parikh,1,1.0,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,2014-10-12,Bill johnson,Warning ..would not see this dentist,Do not go to this dentist office they scam peo...,NaN,2016-09-06 20:54:13
3,12949969,28904504,/dentists/Dr_Aaron_Aguilar,5,5.0,NaN,NaN,NaN,NaN,NaN,...,5.0,5.0,5.0,5.0,2015-06-11,NaN,NaN,Very thoughtful Dr. Communicates/bedside mann...,NaN,2016-09-06 20:54:14
4,12949970,28380953,/dentists/Dr_Aaron_D_Larsen,4,3.0,NaN,NaN,NaN,NaN,NaN,...,4.0,4.0,4.0,5.0,2015-03-31,NaN,Dr larsen great others no,Would continue to see Dr. Larsen however his ...,NaN,2016-09-06 20:54:18

In [12]:
rew_panel.tail()

,Id,review_id,href,overall_rating,Ease_of_Appointment,Promptness,Courteous_Staff,Accurate_Diagnosis,Bedside_Manner,Spends_Time_with_Me,...,Advanced_Technology,Caring_Manner,Pain_Minimized,Satisfaction,date,reviewer,title,content,helpful_vote,crawl_date
1796199,14819364,19546944,/doctors/Dr_Ramy_Doss,5,5.0,4.0,5.0,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,2011-07-13,NaN,NaN,Love Dr. Army Doss. He saved my life- a hea...,NaN,2016-09-16 20:03:44
1796200,14819365,18196930,/doctors/Dr_Ramy_Doss,5,5.0,4.0,5.0,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,2008-06-23,Cheri R,"Wonderful, caring Doctor",I met Dr. Doss during a very stressful time an...,NaN,2016-09-16 20:03:44
1796201,14819366,18233638,/doctors/Dr_Ramy_Doss,5,5.0,4.0,5.0,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,2008-04-30,THERESA DALTON,NaN,IF IT WEREN'T FOR DR. DOSS' ACCURATE DIAGNOSIS...,NaN,2016-09-16 20:03:44
1796202,14819367,19725098,/doctors/Dr_Randall_Edson,5,5.0,4.0,5.0,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,2011-11-21,NaN,NaN,dr. edson is as good as it gets for being pers...,1.0,2016-09-16 20:03:45
1796203,14819368,31104374,/doctors/Dr_Randall_Farrar,5,5.0,5.0,5.0,5.0,5.0,NaN,...,NaN,NaN,NaN,NaN,2015-12-19,NaN,NaN,Great Doc! Really cares.,NaN,2016-09-16 20:03:47